### ISSUE TITLE
Wrong License

### ISSUE THREAD

**Issue by rdoursenaud** [ToManage/TM-CRM_ERP#20]
Your project is GPLv3 not OSL3.

You based your work on Dolibarr which is GPLv3 as can be attested by grepping the word dolibarr in your source code and the overall design of the data structures and views used by the application.
Your work is a derivative of the original Dolibarr work.
You can't change the license without having prior consent from *all* the authors, hence the code is GPLv3.

**Comment by hepr** [comment]
Hi,

This project wasn't based on Dolibarr.
It's an other language, an other framework, an other database manager, on other product

Dolibarr is a very good product. I'm an old contributor so I know it very well.

An other product Speedealing was a fork from dolibarr, but this project was stopped because I stop develop in PHP to start a new project in nodejs.

For information the license of the version 1 of TM would change from OSL to Apache2.

Regards

Herve
